from __future__ import annotations

LATEST_SCENE_CONFIG = {
    "scene_id": "scene_0001",
    "name": "品牌最新一条商品数据查询",
    "description": "围绕品牌、商品名称、上架时间和抓取日期输出最新商品明细，作为主流程入口。",
    "scope": "latest-item-query-config",
    "sample_goals": [
        "查看最新一条商品明细，返回商品ID、商品名称、品牌、类目、价格和上架时间",
        "按品牌查看最新一条商品明细，返回商品ID、商品名称、类目、价格和上架时间",
        "按抓取日期查看最新商品明细，确认最近批次里有哪些商品",
    ],
    "fields": [
        {
            "semantic_name": "商品ID",
            "table_name": "clothing_info",
            "field_name": "Id",
            "role": "filter",
            "required": True,
            "description": "SKU唯一标识，用于精确定位和去重。",
            "aliases": ["Id", "SKU", "商品ID"],
            "unit": "",
            "aggregation": "",
            "er_path": "",
        },
        {
            "semantic_name": "商品名称",
            "table_name": "clothing_info",
            "field_name": "Name",
            "role": "dimension",
            "required": False,
            "description": "商品展示名称，用于输出最新商品明细。",
            "aliases": ["Name", "商品名", "商品名称"],
            "unit": "",
            "aggregation": "",
            "er_path": "",
        },
        {
            "semantic_name": "商品源ID",
            "table_name": "clothing_info",
            "field_name": "ProductId",
            "role": "filter",
            "required": False,
            "description": "来源商品ID，用于辅助识别同源商品。",
            "aliases": ["ProductId", "商品源ID", "源商品ID"],
            "unit": "",
            "aggregation": "",
            "er_path": "",
        },
        {
            "semantic_name": "品牌",
            "table_name": "dict_brand_info",
            "field_name": "Name",
            "role": "dimension",
            "required": True,
            "description": "标准品牌名称，来自品牌字典；通过 dict_brand_info.Code = clothing_info.BrandCode 关联商品。",
            "aliases": ["品牌", "标准品牌", "Brand", "BrandName", "Name", "NameEn", "Alias", "UNIQLO"],
            "unit": "",
            "aggregation": "",
            "er_path": "dict_brand_info.Code = clothing_info.BrandCode",
        },
        {
            "semantic_name": "一级类目",
            "table_name": "clothing_info",
            "field_name": "Category",
            "role": "dimension",
            "required": False,
            "description": "商品一级类目，用于展示和筛选。",
            "aliases": ["Category", "一级类目", "一级品类"],
            "unit": "",
            "aggregation": "",
            "er_path": "",
        },
        {
            "semantic_name": "二级类目",
            "table_name": "clothing_info",
            "field_name": "SubCategory",
            "role": "dimension",
            "required": False,
            "description": "商品二级类目，用于展示和筛选。",
            "aliases": ["SubCategory", "二级类目", "二级品类"],
            "unit": "",
            "aggregation": "",
            "er_path": "",
        },
        {
            "semantic_name": "叶子类目",
            "table_name": "clothing_info",
            "field_name": "LeafCategory",
            "role": "dimension",
            "required": False,
            "description": "更细粒度的商品定位维度。",
            "aliases": ["LeafCategory", "叶子类目"],
            "unit": "",
            "aggregation": "",
            "er_path": "",
        },
        {
            "semantic_name": "价格",
            "table_name": "clothing_info",
            "field_name": "Price",
            "role": "metric",
            "required": True,
            "description": "商品价格，适合最新商品明细与品牌对比。",
            "aliases": ["Price", "价格", "售价"],
            "unit": "price",
            "aggregation": "avg/min/max",
            "er_path": "",
        },
        {
            "semantic_name": "上架时间",
            "table_name": "clothing_info",
            "field_name": "CreateTime",
            "role": "time",
            "required": True,
            "description": "商品上架时间，用于最新一条商品明细定位。",
            "aliases": ["CreateTime", "上架时间", "上新时间"],
            "unit": "",
            "aggregation": "",
            "er_path": "",
        },
        {
            "semantic_name": "抓取日期",
            "table_name": "clothing_info",
            "field_name": "ReceiveTime",
            "role": "time",
            "required": True,
            "description": "数据抓取时间，用于最新抓取批次和近期窗口。",
            "aliases": ["ReceiveTime", "抓取日期", "抓取时间"],
            "unit": "",
            "aggregation": "",
            "er_path": "",
        },
        {
            "semantic_name": "来源站点域名",
            "table_name": "clothing_info",
            "field_name": "SourceUrl",
            "role": "dimension",
            "required": False,
            "description": "来源站点域名，用于追踪最新商品来源。",
            "aliases": ["SourceUrl", "来源站点", "站点域名"],
            "unit": "",
            "aggregation": "",
            "er_path": "",
        },
    ],
    "relations": [
        {
            "left_table": "dict_brand_info",
            "left_field": "Code",
            "right_table": "clothing_info",
            "right_field": "BrandCode",
            "join_type": "LEFT",
            "note": "标准品牌字典到商品主表；品牌筛选和展示优先使用 dict_brand_info.Name。",
        }
    ],
    "metric_templates": [],
    "price_band_template": [],
    "question_matrix": [
        {
            "preset_key": "latest_item_detail",
            "title": "最新商品明细",
            "question": "查看最新一条商品明细，返回商品ID、商品名称、品牌、类目、价格、上架时间和抓取日期",
            "editable": True,
            "field_requirements": [
                {
                    "semantic_name": "商品ID",
                    "table_name": "clothing_info",
                    "field_name": "Id",
                    "role": "filter",
                    "required": True,
                    "purpose": "最新商品去重基准",
                },
                {
                    "semantic_name": "商品名称",
                    "table_name": "clothing_info",
                    "field_name": "Name",
                    "role": "dimension",
                    "required": True,
                    "purpose": "最新商品展示字段",
                },
                {
                    "semantic_name": "品牌",
                    "table_name": "dict_brand_info",
                "field_name": "Name",
                    "role": "dimension",
                    "required": True,
                    "purpose": "品牌展示字段",
                },
                {
                    "semantic_name": "一级类目",
                    "table_name": "clothing_info",
                    "field_name": "Category",
                    "role": "dimension",
                    "required": True,
                    "purpose": "类目展示字段",
                },
                {
                    "semantic_name": "价格",
                    "table_name": "clothing_info",
                    "field_name": "Price",
                    "role": "metric",
                    "required": True,
                    "purpose": "价格展示字段",
                },
                {
                    "semantic_name": "上架时间",
                    "table_name": "clothing_info",
                    "field_name": "CreateTime",
                    "role": "time",
                    "required": True,
                    "purpose": "最新一条定位时间",
                },
                {
                    "semantic_name": "抓取日期",
                    "table_name": "clothing_info",
                    "field_name": "ReceiveTime",
                    "role": "time",
                    "required": True,
                    "purpose": "最新批次辅助时间",
                },
            ],
            "derived_metrics": [],
            "group_by": [],
            "sort": [
                {"metric": "上架时间", "direction": "DESC"},
                {"metric": "抓取日期", "direction": "DESC"},
            ],
            "limit": 1,
            "notes": [
                "这是商品级明细查询，不要使用 COUNT、GROUP BY 或聚合指标；每行应代表一个商品。",
                "没有具体品牌值时，不要臆造品牌过滤条件，直接返回按时间排序的最新一条明细。",
                "最新一条优先按上架时间 CreateTime 定位，必要时再结合抓取日期 ReceiveTime。",
            ],
        }
    ],
    "out_of_scope": [
        "价格带分布",
        "品牌均价排行",
        "平台价差",
        "聚合统计",
    ],
    "notes": [
        "这是主流程入口场景，核心输出是商品级最新明细，不是测试占位场景。",
        "最新商品优先使用 CreateTime 锚点；如果问题明确指向最近抓取批次，再使用 ReceiveTime。",
    ],
}
