from __future__ import annotations

PRICE_SCENE_ID = "scene_prd_price"
PRICE_SCENE_NAME = "商品价格分析"
PRICE_SCENE_DESCRIPTION = "围绕品牌、品类、来源站点和场景标签的价格结构、价格带和价差分析。"

PRICE_SCENE_SAMPLE_GOALS = [
    "各品牌的SKU数、平均价、最低价、最高价和价格跨度是多少，按价格跨度降序返回前20",
    "各一级类目和二级类目的SKU数、平均价和价格跨度是多少，按SKU数降序返回前30",
    "按品牌统计0-99、100-199、200-399、400-799、800+价格带分布和占比",
    "最近抓取批次中各品牌平均价最高的是哪些，返回品牌、SKU数、平均价、最高价",
    "各来源站点域名的品牌覆盖、SKU数和平均价差异是什么",
    "各品牌在不同场景标签下的平均价差异是多少",
]

PRICE_SCENE_FIELDS = [
    {
        "semantic_name": "商品ID",
        "table_name": "clothing_info",
        "field_name": "Id",
        "role": "filter",
        "required": True,
        "description": "SKU唯一标识，用于COUNT DISTINCT和结果去重。",
        "aliases": ["Id", "SKU", "商品ID"],
    },
    {
        "semantic_name": "品牌",
        "table_name": "clothing_info",
        "field_name": "BrandName",
        "role": "dimension",
        "required": True,
        "description": "价格结构对比的核心维度。",
        "aliases": ["BrandName", "品牌"],
    },
    {
        "semantic_name": "一级类目",
        "table_name": "clothing_info",
        "field_name": "Category",
        "role": "dimension",
        "required": False,
        "description": "价格结构的主品类维度。",
        "aliases": ["Category", "一级品类"],
    },
    {
        "semantic_name": "二级类目",
        "table_name": "clothing_info",
        "field_name": "SubCategory",
        "role": "dimension",
        "required": False,
        "description": "用于细分价格结构和竞品定位。",
        "aliases": ["SubCategory", "二级品类"],
    },
    {
        "semantic_name": "价格",
        "table_name": "clothing_info",
        "field_name": "Price",
        "role": "metric",
        "required": True,
        "description": "价格主指标，默认口径为销售价/成交价。",
        "aliases": ["Price", "价格", "售价", "单价"],
    },
    {
        "semantic_name": "抓取日期",
        "table_name": "clothing_info",
        "field_name": "ReceiveTime",
        "role": "time",
        "required": False,
        "description": "用于最近抓取批次和趋势窗口。",
        "aliases": ["ReceiveTime", "抓取时间", "抓取日期"],
    },
    {
        "semantic_name": "来源站点域名",
        "table_name": "clothing_info",
        "field_name": "SourceUrl",
        "role": "dimension",
        "required": False,
        "description": "从 SourceUrl 提取域名口径，用于来源站点对比，不等同于销售平台。",
        "aliases": ["SourceUrl", "来源站点", "站点域名", "source site"],
    },
    {
        "semantic_name": "场景标签",
        "table_name": "clothing_scene_info",
        "field_name": "Scene",
        "role": "filter",
        "required": False,
        "description": "用于场景差异分析，仅在场景维度问题中启用。",
        "aliases": ["Scene", "场景"],
    },
]

PRICE_SCENE_RELATIONS = [
    {
        "left_table": "clothing_info",
        "left_field": "Id",
        "right_table": "clothing_scene_info",
        "right_field": "ClothingId",
        "join_type": "INNER",
        "note": "商品到场景标签的关联，仅在场景维度问题中启用。",
    }
]

PRICE_SCENE_METRIC_TEMPLATES = [
    {
        "name": "SKU数",
        "formula": "COUNT(DISTINCT Id)",
        "description": "去重商品数，适合品牌/品类/来源站点/场景分析。",
    },
    {
        "name": "平均价",
        "formula": "AVG(Price)",
        "description": "商品均价。",
    },
    {
        "name": "最低价",
        "formula": "MIN(Price)",
        "description": "分组内最低价格。",
    },
    {
        "name": "最高价",
        "formula": "MAX(Price)",
        "description": "分组内最高价格。",
    },
    {
        "name": "价格跨度",
        "formula": "MAX(Price) - MIN(Price)",
        "description": "分组内价格区间宽度。",
    },
    {
        "name": "价格带占比",
        "formula": "COUNT(*) / SUM(COUNT(*)) OVER()",
        "description": "按固定价格带分桶后的占比。",
    },
    {
        "name": "品牌覆盖数",
        "formula": "COUNT(DISTINCT BrandName)",
        "description": "来源站点或场景维度下的品牌覆盖。",
    },
]

PRICE_SCENE_PRICE_BANDS = [
    {"band": "0-99", "min": 0, "max": 99},
    {"band": "100-199", "min": 100, "max": 199},
    {"band": "200-399", "min": 200, "max": 399},
    {"band": "400-799", "min": 400, "max": 799},
    {"band": "800+", "min": 800, "max": None},
]

PRICE_SCENE_QUESTION_MATRIX = [
    {
        "preset_key": "brand_price_spread_top20",
        "title": "品牌价格跨度排行",
        "question": "各品牌的SKU数、平均价、最低价、最高价和价格跨度是多少，按价格跨度降序返回前20",
        "editable": True,
        "field_requirements": [
            {
                "semantic_name": "商品ID",
                "table_name": "clothing_info",
                "field_name": "Id",
                "role": "filter",
                "required": True,
                "purpose": "SKU数去重基准",
            },
            {
                "semantic_name": "品牌",
                "table_name": "clothing_info",
                "field_name": "BrandName",
                "role": "dimension",
                "required": True,
                "purpose": "分组维度",
            },
            {
                "semantic_name": "价格",
                "table_name": "clothing_info",
                "field_name": "Price",
                "role": "metric",
                "required": True,
                "purpose": "价格统计指标",
            },
        ],
        "derived_metrics": [
            {"name": "SKU数", "formula": "COUNT(DISTINCT Id)"},
            {"name": "平均价", "formula": "AVG(Price)"},
            {"name": "最低价", "formula": "MIN(Price)"},
            {"name": "最高价", "formula": "MAX(Price)"},
            {"name": "价格跨度", "formula": "MAX(Price) - MIN(Price)"},
        ],
        "group_by": ["品牌"],
        "sort": [{"metric": "价格跨度", "direction": "DESC"}],
        "limit": 20,
        "notes": ["不需要平台字段", "不需要时间筛选"],
    },
    {
        "preset_key": "category_price_spread_top30",
        "title": "类目价格跨度排行",
        "question": "各一级类目和二级类目的SKU数、平均价和价格跨度是多少，按SKU数降序返回前30",
        "editable": True,
        "field_requirements": [
            {
                "semantic_name": "商品ID",
                "table_name": "clothing_info",
                "field_name": "Id",
                "role": "filter",
                "required": True,
                "purpose": "SKU数去重基准",
            },
            {
                "semantic_name": "一级类目",
                "table_name": "clothing_info",
                "field_name": "Category",
                "role": "dimension",
                "required": True,
                "purpose": "一级类目分组",
            },
            {
                "semantic_name": "二级类目",
                "table_name": "clothing_info",
                "field_name": "SubCategory",
                "role": "dimension",
                "required": True,
                "purpose": "二级类目分组",
            },
            {
                "semantic_name": "价格",
                "table_name": "clothing_info",
                "field_name": "Price",
                "role": "metric",
                "required": True,
                "purpose": "价格统计指标",
            },
        ],
        "derived_metrics": [
            {"name": "SKU数", "formula": "COUNT(DISTINCT Id)"},
            {"name": "平均价", "formula": "AVG(Price)"},
            {"name": "价格跨度", "formula": "MAX(Price) - MIN(Price)"},
        ],
        "group_by": ["一级类目", "二级类目"],
        "sort": [{"metric": "SKU数", "direction": "DESC"}],
        "limit": 30,
        "notes": ["不需要平台字段", "不需要时间筛选"],
    },
    {
        "preset_key": "brand_price_band_distribution",
        "title": "品牌价格带分布",
        "question": "按品牌统计0-99、100-199、200-399、400-799、800+价格带分布和占比",
        "editable": True,
        "field_requirements": [
            {
                "semantic_name": "商品ID",
                "table_name": "clothing_info",
                "field_name": "Id",
                "role": "filter",
                "required": True,
                "purpose": "SKU数去重基准",
            },
            {
                "semantic_name": "品牌",
                "table_name": "clothing_info",
                "field_name": "BrandName",
                "role": "dimension",
                "required": True,
                "purpose": "品牌分组",
            },
            {
                "semantic_name": "价格",
                "table_name": "clothing_info",
                "field_name": "Price",
                "role": "metric",
                "required": True,
                "purpose": "价格带分桶依据",
            },
        ],
        "derived_metrics": [
            {"name": "价格带SKU数", "formula": "COUNT(*)"},
            {"name": "价格带占比", "formula": "COUNT(*) / SUM(COUNT(*)) OVER()"},
        ],
        "group_by": ["品牌", "价格带"],
        "sort": [{"metric": "品牌", "direction": "ASC"}],
        "limit": None,
        "notes": ["价格带口径固定", "不要由模型自由改桶宽"],
    },
    {
        "preset_key": "recent_batch_brand_avg_rank",
        "title": "最近批次品牌均价排行",
        "question": "最近抓取批次中各品牌平均价最高的是哪些，返回品牌、SKU数、平均价、最高价",
        "editable": True,
        "field_requirements": [
            {
                "semantic_name": "商品ID",
                "table_name": "clothing_info",
                "field_name": "Id",
                "role": "filter",
                "required": True,
                "purpose": "SKU数去重基准",
            },
            {
                "semantic_name": "品牌",
                "table_name": "clothing_info",
                "field_name": "BrandName",
                "role": "dimension",
                "required": True,
                "purpose": "品牌分组",
            },
            {
                "semantic_name": "价格",
                "table_name": "clothing_info",
                "field_name": "Price",
                "role": "metric",
                "required": True,
                "purpose": "均价与最高价统计",
            },
            {
                "semantic_name": "抓取日期",
                "table_name": "clothing_info",
                "field_name": "ReceiveTime",
                "role": "time",
                "required": True,
                "purpose": "最近抓取批次口径",
            },
        ],
        "derived_metrics": [
            {"name": "SKU数", "formula": "COUNT(DISTINCT Id)"},
            {"name": "平均价", "formula": "AVG(Price)"},
            {"name": "最高价", "formula": "MAX(Price)"},
        ],
        "group_by": ["品牌"],
        "sort": [{"metric": "平均价", "direction": "DESC"}],
        "limit": 20,
        "notes": ["默认以最近抓取批次作为时间口径", "最近抓取批次使用 MAX(DATE(ReceiveTime))，不使用系统当前日期"],
    },
    {
        "preset_key": "source_site_brand_coverage",
        "title": "来源站点品牌覆盖",
        "question": "各来源站点域名的品牌覆盖、SKU数和平均价差异是什么",
        "editable": True,
        "field_requirements": [
            {
                "semantic_name": "商品ID",
                "table_name": "clothing_info",
                "field_name": "Id",
                "role": "filter",
                "required": True,
                "purpose": "SKU数去重基准",
            },
            {
                "semantic_name": "品牌",
                "table_name": "clothing_info",
                "field_name": "BrandName",
                "role": "dimension",
                "required": True,
                "purpose": "品牌覆盖统计",
            },
            {
                "semantic_name": "价格",
                "table_name": "clothing_info",
                "field_name": "Price",
                "role": "metric",
                "required": True,
                "purpose": "均价统计",
            },
            {
                "semantic_name": "来源站点域名",
                "table_name": "clothing_info",
                "field_name": "SourceUrl",
                "role": "dimension",
                "required": True,
                "purpose": "来源站点分组口径，不等同于销售平台",
            },
        ],
        "derived_metrics": [
            {"name": "品牌覆盖数", "formula": "COUNT(DISTINCT BrandName)"},
            {"name": "SKU数", "formula": "COUNT(DISTINCT Id)"},
            {"name": "平均价", "formula": "AVG(Price)"},
        ],
        "group_by": ["来源站点域名"],
        "sort": [{"metric": "品牌覆盖数", "direction": "DESC"}],
        "limit": 20,
        "notes": ["来源站点域名来自 SourceUrl 提取", "不要写成平台价差"],
    },
    {
        "preset_key": "brand_scene_price_diff",
        "title": "品牌场景价格差异",
        "question": "各品牌在不同场景标签下的平均价差异是多少",
        "editable": True,
        "field_requirements": [
            {
                "semantic_name": "商品ID",
                "table_name": "clothing_info",
                "field_name": "Id",
                "role": "filter",
                "required": True,
                "purpose": "SKU数去重基准",
            },
            {
                "semantic_name": "品牌",
                "table_name": "clothing_info",
                "field_name": "BrandName",
                "role": "dimension",
                "required": True,
                "purpose": "品牌分组",
            },
            {
                "semantic_name": "价格",
                "table_name": "clothing_info",
                "field_name": "Price",
                "role": "metric",
                "required": True,
                "purpose": "均价统计",
            },
            {
                "semantic_name": "场景标签",
                "table_name": "clothing_scene_info",
                "field_name": "Scene",
                "role": "filter",
                "required": True,
                "purpose": "场景维度分组",
            },
        ],
        "derived_metrics": [
            {"name": "SKU数", "formula": "COUNT(DISTINCT Id)"},
            {"name": "平均价", "formula": "AVG(Price)"},
            {"name": "品牌内场景价差", "formula": "同一品牌在不同场景标签下的平均价极差"},
        ],
        "group_by": ["品牌", "场景标签"],
        "sort": [{"metric": "品牌内场景价差", "direction": "DESC"}],
        "limit": 20,
        "notes": ["场景维度，不要改写成平台维度"],
    },
]

PRICE_SCENE_REGRESSION_QUESTIONS = [item["question"] for item in PRICE_SCENE_QUESTION_MATRIX]

PRICE_SCENE_OUT_OF_SCOPE = [
    "平台销售价差",
    "没有来源站点域名支撑的渠道对比",
    "依赖实时销量或库存的分析",
]
